name: Build and Push Docker Image

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+.itb.[0-9]+
  repository_dispatch:
    types:
      - dispatch-build

jobs:

  build:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'osg-htc/')

    steps:
    - uses: actions/checkout@v2

    - name: Generate tag list
      id: generate-tag-list
      run: |
        docker_repo=${GITHUB_REPOSITORY/osg-htc/opensciencegrid}
        GITHUB_TAG=${GITHUB_REF##*/v}
        
        # If this is a itb release lets tag it as such
        if [[ $GITHUB_TAG == *"itb"* ]]; 
        then
          ITB_SUFFIX="-itb"
        else
          ITB_SUFFIX=""
        fi
        
        tag_list=()
        for registry in hub.opensciencegrid.org docker.io; do
          for image_tag in "latest${ITB_SUFFIX}" "${GITHUB_TAG}"; do
            tag_list+=("$registry/$docker_repo":"$image_tag")
          done
        done
        # This causes the tag_list array to be comma-separated below,
        # which is required for build-push-action
        IFS=,
        echo "::set-output name=taglist::${tag_list[*]}"        

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      continue-on-error: true
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to OSG Harbor
      uses: docker/login-action@v1
      with:
        registry: hub.opensciencegrid.org
        username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
        password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.0
      with:
        context: .
        push: true
        tags: "${{ steps.generate-tag-list.outputs.taglist }}"